const std = @import("std");
const root_fs = @import("debz").root_fs;
const foundation = @import("native_test_foundation.zig");
const support = @import("native_lifecycle_support.zig");

const name = "diversion-lifecycle";
const base = "usr/share/" ++ name;
const literal = "etc/diversion\\literal";
const hook =
    \\replacement="/diversion-$DPKG_MAINTSCRIPT_NAME-replace"
    \\if [ -f "$replacement" ]; then
    \\    /diversion-mv "$replacement" /var/lib/dpkg/diversions || exit 26
    \\fi
    \\if [ "$DPKG_MAINTSCRIPT_NAME" = preinst ] && [ -f /diversion-helper-record ]; then
    \\    {
    \\        IFS= read -r source || exit 27
    \\        IFS= read -r destination || exit 27
    \\    } < /diversion-helper-record
    \\    /diversion-helper --local --no-rename --remove "$source" || exit 28
    \\    /diversion-helper --local --no-rename --divert "$destination" --add "$source" || exit 28
    \\fi
    \\inplace="/diversion-$DPKG_MAINTSCRIPT_NAME-inplace"
    \\if [ "$DPKG_MAINTSCRIPT_NAME" = preinst ] && [ -f /diversion-inplace-record ]; then
    \\    inplace=/diversion-inplace-record
    \\fi
    \\if [ -f "$inplace" ]; then
    \\    while IFS= read -r line; do
    \\        printf '%s\n' "$line"
    \\    done < "$inplace" > /var/lib/dpkg/diversions
    \\fi
    \\
;

fn archive(fixture: *foundation.Fixture, arch: []const u8, version: []const u8, changed_link: bool) ![]u8 {
    const conf = try std.fmt.allocPrint(fixture.allocator, "configuration {s}\n", .{version});
    defer fixture.allocator.free(conf);
    const extra = try std.fmt.allocPrint(fixture.allocator, "literal version {s}\n", .{version});
    defer fixture.allocator.free(extra);
    const result = try support.makePackage(fixture, arch, version, name, if (changed_link) "packages/diversion-link" else "packages/diversion-lifecycle", .{
        .full_payload = true,
        .conffile_content = conf,
        .extra_files = &.{.{ .path = literal, .content = extra }},
        .scripts = .{ .before_failure = hook },
    });
    if (changed_link and std.mem.eql(u8, version, "2")) {
        // The package source is rebuilt after changing the link; archive checksums remain generated by buildPackage.
        const stem = try std.fmt.allocPrint(fixture.allocator, "packages/diversion-link/{s}_{s}_data.source", .{ name, version });
        defer fixture.allocator.free(stem);
        const link = try support.path(fixture.allocator, stem, base ++ "/current");
        defer fixture.allocator.free(link);
        try fixture.dir.deleteFile(fixture.io, link);
        try fixture.dir.symLink(fixture.io, "data.link", link, .{});
        const destination = try std.fmt.allocPrint(fixture.allocator, "packages/diversion-link/{s}_{s}_data.deb", .{ name, version });
        defer fixture.allocator.free(destination);
        const rebuilt = try fixture.buildPackage(stem, destination, .{});
        fixture.allocator.free(result);
        return rebuilt;
    }
    return result;
}

fn record(fixture: *foundation.Fixture, source: []const u8, destination: []const u8, owner: []const u8) ![]u8 {
    return std.fmt.allocPrint(fixture.allocator, "/{s}\n/{s}\n{s}\n", .{ source, destination, owner });
}

fn both(case: *support.Scenario, relative: []const u8, content: []const u8) !void {
    for ([_][]const u8{ "reference", "native" }) |side| {
        const target = try std.fmt.allocPrint(case.fixture.allocator, "{s}/{s}/{s}", .{ case.name, side, relative });
        defer case.fixture.allocator.free(target);
        try support.fixtureFile(case.fixture, target, content, 0o644);
    }
}

fn seed(case: *support.Scenario, records: []const u8) !void {
    try both(case, "var/lib/dpkg/diversions", records);
}

fn marker(case: *support.Scenario, kind: []const u8, content: []const u8, atomic: bool) !void {
    if (atomic) for ([_][]const u8{ "reference", "native" }) |side| {
        const root = try support.path(case.fixture.allocator, case.name, side);
        defer case.fixture.allocator.free(root);
        try support.copyProgram(case.fixture, root, "/bin/mv", "/diversion-mv");
    };
    const relative = try std.fmt.allocPrint(case.fixture.allocator, "diversion-{s}-{s}", .{ kind, if (atomic) "replace" else "inplace" });
    defer case.fixture.allocator.free(relative);
    try both(case, relative, content);
}

fn chosen(arch: []const u8) [1]foundation.PackageIdentity {
    return .{.{ .name = name, .architecture = arch }};
}

fn assertListed(case: *support.Scenario, source: []const u8, destination: []const u8) !void {
    for ([_][]const u8{ "reference", "native" }) |side| {
        const relative = try std.fmt.allocPrint(case.fixture.allocator, "{s}/{s}/var/lib/dpkg/info/{s}.list", .{ case.name, side, name });
        defer case.fixture.allocator.free(relative);
        const text = try support.read(case.fixture, relative, 1024 * 1024);
        defer case.fixture.allocator.free(text);
        const match = try std.fmt.allocPrint(case.fixture.allocator, "/{s}\n", .{source});
        defer case.fixture.allocator.free(match);
        const shifted = try std.fmt.allocPrint(case.fixture.allocator, "/{s}\n", .{destination});
        defer case.fixture.allocator.free(shifted);
        if (std.mem.indexOf(u8, text, match) == null or std.mem.indexOf(u8, text, shifted) != null)
            return error.WrongLogicalPackageList;
    }
}

fn staticRoutes(fixture: *foundation.Fixture, driver: []const u8, dpkg: []const u8, arch: []const u8, first: []const u8, second: []const u8) !void {
    const selection = chosen(arch);
    for ([_]struct { label: []const u8, member: []const u8, owner: []const u8, override: []const u8 = "" }{
        .{ .label = "local", .member = "mode", .owner = ":" },
        .{ .label = "other-package", .member = "mode", .owner = "wrapper" },
        .{ .label = "exempt-package", .member = "mode", .owner = name },
        .{ .label = "qualified-owner", .member = "mode", .owner = name ++ ":ARCH" },
        .{ .label = "symlink", .member = "current", .owner = ":" },
        .{ .label = "hardlink-source", .member = "data", .owner = ":" },
        .{ .label = "hardlink-member", .member = "data.link", .owner = ":" },
        .{ .label = "directory", .member = "empty", .owner = ":" },
        .{ .label = "literal", .member = literal, .owner = ":" },
        .{ .label = "conffile", .member = "etc/debz-native.conf", .owner = ":" },
        .{ .label = "override-source", .member = "mode", .owner = ":", .override = "#42420 #42421 4750 /" ++ base ++ "/mode\n" },
        .{ .label = "override-destination", .member = "mode", .owner = ":", .override = "#42420 #42421 4750 /" ++ base ++ "/mode.distrib\n" },
    }) |entry| {
        const label = try std.fmt.allocPrint(fixture.allocator, "diversion-{s}", .{entry.label});
        defer fixture.allocator.free(label);
        var case = try support.Scenario.init(fixture, label, driver, dpkg, arch, false);
        defer case.deinit();
        const source = if (std.mem.startsWith(u8, entry.member, "etc/"))
            try fixture.allocator.dupe(u8, entry.member)
        else
            try std.fmt.allocPrint(fixture.allocator, "{s}/{s}", .{ base, entry.member });
        defer fixture.allocator.free(source);
        const destination = try std.fmt.allocPrint(fixture.allocator, "{s}.distrib", .{source});
        defer fixture.allocator.free(destination);
        const owner = if (std.mem.endsWith(u8, entry.owner, ":ARCH"))
            try std.fmt.allocPrint(fixture.allocator, "{s}:{s}", .{ name, arch })
        else
            try fixture.allocator.dupe(u8, entry.owner);
        defer fixture.allocator.free(owner);
        const records = try record(fixture, source, destination, owner);
        defer fixture.allocator.free(records);
        try seed(&case, records);
        try both(&case, "var/lib/dpkg/statoverride", entry.override);
        if (!std.mem.eql(u8, entry.label, "directory")) try both(&case, source, "administrator payload\n");
        for ([_][]const u8{ "install", "upgrade", "reinstall", "downgrade" }, [_][]const u8{ first, second, second, first }) |operation, selected_archive| {
            try case.phase(.{ .operation = operation, .archives = &.{selected_archive}, .packages = &selection }, false);
            try assertListed(&case, source, destination);
            for ([_][]const u8{ case.reference_root, case.native_root }) |root| {
                const logical = if (std.mem.eql(u8, owner, name)) source else destination;
                const physical = try std.fmt.allocPrint(fixture.allocator, "{s}/{s}", .{ root, logical });
                defer fixture.allocator.free(physical);
                _ = try std.Io.Dir.cwd().statFile(fixture.io, physical, .{ .follow_symlinks = false });
            }
        }
        try case.phase(.{ .operation = "remove", .packages = &selection }, false);
        try case.phase(.{ .operation = "purge", .packages = &selection }, false);
        for ([_][]const u8{ "reference", "native" }) |side| {
            const path = try std.fmt.allocPrint(fixture.allocator, "{s}/{s}/var/lib/dpkg/diversions", .{ case.name, side });
            defer fixture.allocator.free(path);
            const stored = try support.read(fixture, path, 1024 * 1024);
            defer fixture.allocator.free(stored);
            if (!std.mem.eql(u8, stored, records)) return error.DiversionDatabaseChanged;
        }
    }
}

fn unsafeRoutes(fixture: *foundation.Fixture, driver: []const u8, dpkg: []const u8, arch: []const u8, first: []const u8) !void {
    const source = base ++ "/mode";
    const original = try record(fixture, source, source ++ ".original", ":");
    defer fixture.allocator.free(original);
    for ([_]struct { label: []const u8, records: []const u8, detail: []const u8, pristine: bool = false }{
        .{ .label = "duplicate", .records = "/" ++ source ++ "\n/" ++ source ++ ".first\n:\n/" ++ source ++ "\n/" ++ source ++ ".second\n:\n", .detail = "invalid_diversion", .pristine = true },
        .{ .label = "chain", .records = "/" ++ source ++ "\n/" ++ source ++ ".first\n:\n/" ++ source ++ ".first\n/" ++ source ++ ".second\n:\n", .detail = "invalid_diversion", .pristine = true },
        .{ .label = "missing-parent", .records = "/" ++ source ++ "\n/opt/diverted/mode\n:\n", .detail = "prefix_transition_unsafe" },
        .{ .label = "directory-parent", .records = "/" ++ base ++ "\n/" ++ base ++ ".distrib\n:\n", .detail = "prefix_transition_unsafe" },
        .{ .label = "destination-member", .records = "/" ++ source ++ "\n/" ++ base ++ "/data\n:\n", .detail = "invalid_diversion" },
        .{ .label = "direct-destination", .records = "/usr/share/unshipped-file\n/" ++ source ++ "\n:\n", .detail = "invalid_diversion" },
        .{ .label = "reserved-destination", .records = "/" ++ source ++ "\n/var/lib/dpkg/diversions\n:\n", .detail = "invalid_diversion", .pristine = true },
        .{ .label = "private-destination", .records = "/" ++ source ++ "\n/var/lib/debz/root-operation-v1.json\n:\n", .detail = "invalid_diversion", .pristine = true },
        .{ .label = "malformed-inplace", .records = original, .detail = "invalid_diversion_update" },
    }) |entry| {
        const label = try std.fmt.allocPrint(fixture.allocator, "diversion-refusal-{s}", .{entry.label});
        defer fixture.allocator.free(label);
        var case = try support.Scenario.init(fixture, label, driver, dpkg, arch, false);
        defer case.deinit();
        const diversions = try std.fmt.allocPrint(fixture.allocator, "{s}/native/var/lib/dpkg/diversions", .{label});
        defer fixture.allocator.free(diversions);
        try support.fixtureFile(fixture, diversions, entry.records, 0o644);
        if (std.mem.eql(u8, entry.label, "malformed-inplace")) {
            const bad = try std.fmt.allocPrint(fixture.allocator, "{s}/native/diversion-preinst-inplace", .{label});
            defer fixture.allocator.free(bad);
            try support.fixtureFile(fixture, bad, "incomplete-record\n", 0o644);
        }
        const status = try std.fmt.allocPrint(fixture.allocator, "{s}/native/var/lib/dpkg/status", .{label});
        defer fixture.allocator.free(status);
        const before_status = try support.read(fixture, status, 64 * 1024 * 1024);
        defer fixture.allocator.free(before_status);
        const trace = try std.fmt.allocPrint(fixture.allocator, "{s}/native/{s}", .{ label, support.trace });
        defer fixture.allocator.free(trace);
        const before_trace = try support.read(fixture, trace, 16 * 1024 * 1024);
        defer fixture.allocator.free(before_trace);
        const destination = try support.path(fixture.allocator, label, "refusal");
        defer fixture.allocator.free(destination);
        try fixture.directory(destination);
        const selection = chosen(arch);
        var result = try support.native(fixture, driver, case.native_root, arch, .{
            .operation = "install",
            .archives = &.{first},
            .packages = &selection,
        }, destination);
        defer result.deinit();
        if (!(std.mem.eql(u8, result.value.outcome, "refused") or std.mem.eql(u8, result.value.outcome, "recovery_required")) or
            !std.mem.eql(u8, result.value.detail, entry.detail))
            return error.UnexpectedDiversionRefusal;
        const payload = try std.fmt.allocPrint(fixture.allocator, "{s}/native/{s}", .{ label, source });
        defer fixture.allocator.free(payload);
        try support.absent(fixture, payload);
        if (entry.pristine) {
            const after_status = try support.read(fixture, status, 64 * 1024 * 1024);
            defer fixture.allocator.free(after_status);
            const after_trace = try support.read(fixture, trace, 16 * 1024 * 1024);
            defer fixture.allocator.free(after_trace);
            const after_record = try support.read(fixture, diversions, 1024 * 1024);
            defer fixture.allocator.free(after_record);
            if (!std.mem.eql(u8, after_status, before_status) or !std.mem.eql(u8, after_trace, before_trace) or
                !std.mem.eql(u8, after_record, entry.records)) return error.RefusalChangedRoot;
            try support.assertNoActiveEvidence(fixture, case.native_root);
        }
    }
}

fn dynamicRoutes(fixture: *foundation.Fixture, driver: []const u8, dpkg: []const u8, arch: []const u8, first: []const u8, second: []const u8) !void {
    const selection = chosen(arch);
    const source = base ++ "/mode";
    const original = try record(fixture, source, source ++ ".original", ":");
    defer fixture.allocator.free(original);
    const changed = try record(fixture, source, source ++ ".changed", ":");
    defer fixture.allocator.free(changed);
    {
        var case = try support.Scenario.init(fixture, "diversion-genuine-helper", driver, dpkg, arch, false);
        defer case.deinit();
        try seed(&case, original);
        for ([_][]const u8{ "reference", "native" }) |side| {
            const root = try support.path(fixture.allocator, case.name, side);
            defer fixture.allocator.free(root);
            try support.copyProgram(fixture, root, "/usr/bin/dpkg-divert", "/diversion-helper");
        }
        try both(&case, "diversion-helper-record", "/" ++ source ++ "\n/" ++ source ++ ".changed\n");
        try case.phase(.{ .operation = "install", .archives = &.{first}, .packages = &selection }, false);
        try case.phase(.{ .operation = "upgrade", .archives = &.{second}, .packages = &selection }, false);
        try case.phase(.{ .operation = "remove", .packages = &selection }, false);
        try case.phase(.{ .operation = "purge", .packages = &selection }, false);
    }
    for ([_]struct { label: []const u8, source: []const u8, destination: []const u8 }{
        .{ .label = "existing-parent-file", .source = source, .destination = "opt/diverted-mode" },
        .{ .label = "existing-parent-link", .source = base ++ "/data", .destination = "opt/diverted-data" },
        .{ .label = "existing-parent-conffile", .source = "etc/debz-native.conf", .destination = "opt/diverted.conf" },
        .{ .label = "existing-source-directory", .source = base, .destination = base ++ ".distrib" },
    }) |entry| {
        const label = try std.fmt.allocPrint(fixture.allocator, "diversion-{s}", .{entry.label});
        defer fixture.allocator.free(label);
        var case = try support.Scenario.init(fixture, label, driver, dpkg, arch, false);
        defer case.deinit();
        const records = try record(fixture, entry.source, entry.destination, ":");
        defer fixture.allocator.free(records);
        try seed(&case, records);
        for ([_][]const u8{ "reference", "native" }) |side| {
            const opt = try std.fmt.allocPrint(fixture.allocator, "{s}/{s}/opt", .{ case.name, side });
            defer fixture.allocator.free(opt);
            try fixture.directory(opt);
        }
        if (std.mem.eql(u8, entry.label, "existing-source-directory")) {
            try both(&case, base ++ "/administrator-file", "administrator payload\n");
        }
        for ([_][]const u8{ "install", "upgrade", "remove", "purge" }, [_]?[]const u8{ first, second, null, null }) |operation, selected_archive| {
            try case.phase(.{
                .operation = operation,
                .archives = if (selected_archive) |a| &.{a} else &.{},
                .packages = &selection,
            }, false);
        }
    }
    for ([_]struct { label: []const u8, operation: []const u8, kind: []const u8, conffile: bool = false, empty: bool = false }{
        .{ .label = "install", .operation = "install", .kind = "preinst" },
        .{ .label = "upgrade", .operation = "upgrade", .kind = "preinst" },
        .{ .label = "postinst", .operation = "install", .kind = "postinst" },
        .{ .label = "remove", .operation = "remove", .kind = "prerm" },
        .{ .label = "empty", .operation = "install", .kind = "preinst", .empty = true },
        .{ .label = "conffile", .operation = "upgrade", .kind = "preinst", .conffile = true },
    }) |entry| {
        const label = try std.fmt.allocPrint(fixture.allocator, "diversion-cache-{s}", .{entry.label});
        defer fixture.allocator.free(label);
        var case = try support.Scenario.init(fixture, label, driver, dpkg, arch, false);
        defer case.deinit();
        const routed = if (entry.conffile) "etc/debz-native.conf" else source;
        const initial = try record(fixture, routed, try std.fmt.allocPrint(fixture.allocator, "{s}.original", .{routed}), ":");
        defer fixture.allocator.free(initial);
        const next = try record(fixture, routed, try std.fmt.allocPrint(fixture.allocator, "{s}.changed", .{routed}), ":");
        defer fixture.allocator.free(next);
        try seed(&case, initial);
        if (!std.mem.eql(u8, entry.operation, "install")) try case.seed(first);
        try marker(&case, entry.kind, if (entry.empty) "" else next, false);
        const selected_archive: ?[]const u8 = if (std.mem.eql(u8, entry.operation, "upgrade")) second else if (std.mem.eql(u8, entry.operation, "remove")) null else first;
        try case.phase(.{
            .operation = entry.operation,
            .archives = if (selected_archive) |a| &.{a} else &.{},
            .packages = &selection,
        }, false);
        if (!std.mem.eql(u8, entry.operation, "remove")) {
            try case.phase(.{ .operation = "reinstall", .archives = &.{selected_archive.?}, .packages = &selection }, false);
            try case.phase(.{ .operation = "remove", .packages = &selection }, false);
        }
        try case.phase(.{ .operation = "purge", .packages = &selection }, false);
    }
    {
        var case = try support.Scenario.init(fixture, "diversion-cache-atomic-then-inplace", driver, dpkg, arch, false);
        defer case.deinit();
        try seed(&case, original);
        const atomic = try record(fixture, source, source ++ ".atomic", ":");
        defer fixture.allocator.free(atomic);
        try marker(&case, "preinst", atomic, true);
        try marker(&case, "postinst", changed, false);
        try case.phase(.{ .operation = "install", .archives = &.{first}, .packages = &selection }, false);
        try case.phase(.{ .operation = "reinstall", .archives = &.{first}, .packages = &selection }, false);
        try case.phase(.{ .operation = "remove", .packages = &selection }, false);
        try case.phase(.{ .operation = "purge", .packages = &selection }, false);
    }
    for ([_]struct { kind: []const u8, present: bool }{
        .{ .kind = "preinst", .present = true },
        .{ .kind = "preinst", .present = false },
        .{ .kind = "postinst", .present = true },
    }) |entry| {
        const label = try std.fmt.allocPrint(fixture.allocator, "diversion-{s}-initial-{s}", .{ entry.kind, if (entry.present) "true" else "false" });
        defer fixture.allocator.free(label);
        var case = try support.Scenario.init(fixture, label, driver, dpkg, arch, false);
        defer case.deinit();
        if (entry.present) try seed(&case, original);
        try marker(&case, entry.kind, changed, true);
        try case.phase(.{ .operation = "install", .archives = &.{first}, .packages = &selection }, false);
        try case.phase(.{ .operation = "reinstall", .archives = &.{first}, .packages = &selection }, false);
        try case.phase(.{ .operation = "remove", .packages = &selection }, false);
        try case.phase(.{ .operation = "purge", .packages = &selection }, false);
    }
}

fn failures(case: *support.Scenario, messages: []const []const u8) !void {
    const text = try std.mem.join(case.fixture.allocator, "\n", messages);
    defer case.fixture.allocator.free(text);
    const content = try std.fmt.allocPrint(case.fixture.allocator, "{s}\n", .{text});
    defer case.fixture.allocator.free(content);
    try both(case, support.failure, content);
}

fn failureRoutes(fixture: *foundation.Fixture, driver: []const u8, dpkg: []const u8, arch: []const u8, first: []const u8, second: []const u8) !void {
    const selection = chosen(arch);
    const changed_archive = try archive(fixture, arch, "2", true);
    defer fixture.allocator.free(changed_archive);
    for ([_][]const u8{ "mode", "current", "data", "data.link", "introduced", "conffile" }) |member| {
        const label = try std.fmt.allocPrint(fixture.allocator, "unchanged-diversion-failure-{s}", .{member});
        defer fixture.allocator.free(label);
        var case = try support.Scenario.init(fixture, label, driver, dpkg, arch, false);
        defer case.deinit();
        const source = if (std.mem.eql(u8, member, "conffile")) "etc/debz-native.conf" else try std.fmt.allocPrint(fixture.allocator, "{s}/{s}", .{ base, member });
        defer if (!std.mem.eql(u8, member, "conffile")) fixture.allocator.free(source);
        const destination = try std.fmt.allocPrint(fixture.allocator, "{s}.original", .{source});
        defer fixture.allocator.free(destination);
        const records = try record(fixture, source, destination, ":");
        defer fixture.allocator.free(records);
        try seed(&case, records);
        try case.seed(first);
        try failures(&case, &.{ name ++ "@1:postrm:upgrade", name ++ "@2:postrm:failed-upgrade" });
        const created = try std.fmt.allocPrint(fixture.allocator, "{s}.dpkg-tmp", .{destination});
        defer fixture.allocator.free(created);
        try case.phase(.{
            .operation = "upgrade",
            .archives = &.{changed_archive},
            .packages = &selection,
            .rollback_links = if (std.mem.eql(u8, member, "current")) &.{} else &.{base ++ "/current"},
            .created_rollback_links = if (std.mem.eql(u8, member, "current")) &.{created} else &.{},
        }, true);
        for ([_][]const u8{ "reference", "native" }) |side| {
            const status_path = try std.fmt.allocPrint(fixture.allocator, "{s}/{s}/var/lib/dpkg/status", .{ label, side });
            defer fixture.allocator.free(status_path);
            const status = try support.read(fixture, status_path, 64 * 1024 * 1024);
            defer fixture.allocator.free(status);
            if (std.mem.indexOf(u8, status, "Version: 1\n") == null) return error.WrongFailureStatus;
            const record_path = try std.fmt.allocPrint(fixture.allocator, "{s}/{s}/var/lib/dpkg/diversions", .{ label, side });
            defer fixture.allocator.free(record_path);
            const stored = try support.read(fixture, record_path, 64 * 1024);
            defer fixture.allocator.free(stored);
            if (!std.mem.eql(u8, stored, records)) return error.DiversionDatabaseChanged;
        }
    }

    const source = base ++ "/mode";
    const original = try record(fixture, source, source ++ ".original", ":");
    defer fixture.allocator.free(original);
    const changed = try record(fixture, source, source ++ ".changed", ":");
    defer fixture.allocator.free(changed);
    for ([_][]const u8{ "success", "failure", "double-failure" }) |outcome| {
        const label = try std.fmt.allocPrint(fixture.allocator, "diversion-refusal-mid-unpack-{s}", .{outcome});
        defer fixture.allocator.free(label);
        var case = try support.Scenario.init(fixture, label, driver, dpkg, arch, false);
        defer case.deinit();
        try seed(&case, original);
        try case.seed(first);
        if (std.mem.eql(u8, outcome, "failure")) try failures(&case, &.{name ++ "@1:postrm:upgrade"}) else if (std.mem.eql(u8, outcome, "double-failure"))
            try failures(&case, &.{ name ++ "@1:postrm:upgrade", name ++ "@2:postrm:failed-upgrade" });
        const moved = try std.fmt.allocPrint(fixture.allocator, "{s}/native/diversion-postrm-replace", .{label});
        defer fixture.allocator.free(moved);
        try support.copyProgram(fixture, try support.path(fixture.allocator, label, "native"), "/bin/mv", "/diversion-mv");
        try support.fixtureFile(fixture, moved, changed, 0o644);
        const destination = try support.path(fixture.allocator, label, "refusal");
        defer fixture.allocator.free(destination);
        try fixture.directory(destination);
        var result = try support.native(fixture, driver, case.native_root, arch, .{
            .operation = "upgrade",
            .archives = &.{second},
            .packages = &selection,
        }, destination);
        defer result.deinit();
        if (!std.mem.eql(u8, result.value.outcome, "recovery_required") or
            !std.mem.eql(u8, result.value.detail, "unsupported_mid_unpack_diversion_update"))
            return error.UnexpectedMidUnpackOutcome;
        const shifted = try std.fmt.allocPrint(fixture.allocator, "{s}/native/{s}.changed", .{ label, source });
        defer fixture.allocator.free(shifted);
        try support.absent(fixture, shifted);
    }
}

fn modeBoth(case: *support.Scenario, relative: []const u8, content: []const u8, mode: u32) !void {
    for ([_][]const u8{ "reference", "native" }) |side| {
        const path = try std.fmt.allocPrint(case.fixture.allocator, "{s}/{s}/{s}", .{ case.name, side, relative });
        defer case.fixture.allocator.free(path);
        try support.fixtureFile(case.fixture, path, content, mode);
    }
}

fn conffileRoutes(fixture: *foundation.Fixture, driver: []const u8, dpkg: []const u8, arch: []const u8, first: []const u8, second: []const u8) !void {
    const selection = chosen(arch);
    const source = "etc/debz-native.conf";
    for ([_][]const u8{ "keep_existing", "use_package_version" }) |policy| {
        for ([_]bool{ true, false }) |update| {
            const label = try std.fmt.allocPrint(fixture.allocator, "diversion-conffile-{s}-{s}", .{ if (update) "update" else "static", policy });
            defer fixture.allocator.free(label);
            var case = try support.Scenario.init(fixture, label, driver, dpkg, arch, false);
            defer case.deinit();
            const destination = try std.fmt.allocPrint(fixture.allocator, "{s}.{s}", .{ source, if (update) "original" else "distrib" });
            defer fixture.allocator.free(destination);
            const records = try record(fixture, source, destination, ":");
            defer fixture.allocator.free(records);
            try seed(&case, records);
            try case.seed(first);
            try modeBoth(&case, destination, "administrator configuration\n", 0o600);
            if (update) {
                const next = try record(fixture, source, source ++ ".changed", ":");
                defer fixture.allocator.free(next);
                try marker(&case, "preinst", next, true);
            }
            try case.phase(.{ .operation = "upgrade", .archives = &.{second}, .packages = &selection, .policy = policy }, false);
            if (update) try case.phase(.{ .operation = "remove", .packages = &selection, .policy = policy }, false);
            try case.phase(.{ .operation = "purge", .packages = &selection, .policy = policy }, false);
        }
    }
}

fn aliasRoutes(fixture: *foundation.Fixture, driver: []const u8, dpkg: []const u8, arch: []const u8) !void {
    const selection = chosen(arch);
    const initial_owner = try support.makePackage(fixture, arch, "1", "alias-owner", "packages/diversion-alias-owner", .{});
    defer fixture.allocator.free(initial_owner);
    const owner_source = "packages/diversion-alias-owner/alias-owner_1_data.source";
    try fixture.directory(owner_source ++ "/bin");
    const alias_owner = try fixture.buildPackage(owner_source, "packages/diversion-alias-owner/alias-owner_1_data.deb", .{});
    defer fixture.allocator.free(alias_owner);
    for ([_][]const u8{ "bin", "usr/bin" }) |spelling| {
        const suffix = if (std.mem.eql(u8, spelling, "bin")) "bin" else "usr-bin";
        const source = try std.fmt.allocPrint(fixture.allocator, "{s}/diversion-mode", .{spelling});
        defer fixture.allocator.free(source);
        const destination = "bin/diversion-mode.distrib";
        const alias_archive = try support.makePackage(fixture, arch, "1", name, try std.fmt.allocPrint(fixture.allocator, "packages/diversion-alias-{s}", .{suffix}), .{
            .extra_files = &.{.{ .path = source, .content = "aliased diversion\n" }},
            .scripts = .{ .before_failure = hook },
        });
        defer fixture.allocator.free(alias_archive);
        const label = try std.fmt.allocPrint(fixture.allocator, "diversion-alias-{s}", .{suffix});
        defer fixture.allocator.free(label);
        var case = try support.Scenario.init(fixture, label, driver, dpkg, arch, false);
        defer case.deinit();
        const records = try record(fixture, source, destination, ":");
        defer fixture.allocator.free(records);
        for ([_][]const u8{ "reference", "native" }, [_][]const u8{ case.reference_root, case.native_root }) |side, path| {
            const relative = try support.path(fixture.allocator, label, side);
            defer fixture.allocator.free(relative);
            const usr = try support.path(fixture.allocator, relative, "usr");
            defer fixture.allocator.free(usr);
            try fixture.directory(usr);
            const old = try support.path(fixture.allocator, relative, "bin");
            defer fixture.allocator.free(old);
            const new = try support.path(fixture.allocator, relative, "usr/bin");
            defer fixture.allocator.free(new);
            try fixture.dir.rename(old, fixture.dir, new, fixture.io);
            try fixture.dir.symLink(fixture.io, "usr/bin", old, .{});
            var root = try foundation.guardedRoot(fixture.io, path);
            defer root.close(fixture.io);
            try (root_fs.Root.init(fixture.io, root)).applyMetadata(try root_fs.Path.init("bin"), .{
                .modified_nanoseconds = foundation.epoch * std.time.ns_per_s,
            });
        }
        try seed(&case, records);
        try both(&case, "usr/bin/diversion-mode", "administrator payload\n");
        try case.seed(alias_owner);
        try case.phase(.{ .operation = "install", .archives = &.{alias_archive}, .packages = &selection }, false);
        try case.phase(.{ .operation = "reinstall", .archives = &.{alias_archive}, .packages = &selection }, false);
        try case.phase(.{ .operation = "remove", .packages = &selection }, false);
        try case.phase(.{ .operation = "purge", .packages = &selection }, false);
    }
}

fn backupScript(fixture: *foundation.Fixture, version: []const u8, suffix: []const u8) ![]u8 {
    return std.fmt.allocPrint(fixture.allocator,
        \\if [ "$DPKG_MAINTSCRIPT_NAME" = preinst ] && [ "$1" = upgrade ]; then
        \\    /backup-probe-stat --printf='%d:%i\n' /{s}/data{s} /{s}/current > /backup-before || exit 31
        \\fi
        \\if [ "$DPKG_MAINTSCRIPT_NAME" = postrm ] && [ "$1" = upgrade ]; then
        \\    {{
        \\        IFS= read -r original_data || exit 32
        \\        IFS= read -r original_symlink || exit 32
        \\    }} < /backup-before
        \\    [ "$(/backup-probe-stat --printf='%d:%i' /{s}/data{s}.dpkg-tmp)" = "$original_data" ] || exit 33
        \\    [ "$(/backup-probe-stat --printf='%d:%i' /{s}/data.link.dpkg-tmp)" = "$original_data" ] || exit 34
        \\    [ -L /{s}/current.dpkg-tmp ] || exit 35
        \\    [ "$(/backup-probe-stat --printf='%d:%i' /{s}/current.dpkg-tmp)" != "$original_symlink" ] || exit 36
        \\    [ "$(/backup-probe-stat --printf='%a:%u:%g:%Y' /{s}/mode.dpkg-tmp)" = '{s}:0:0:1700000000' ] || exit 37
        \\    IFS= read -r previous < /{s}/data{s}.dpkg-tmp || exit 38
        \\    [ "$previous" = 'data version {s}' ] || exit 39
        \\    [ ! -e /etc/debz-native.conf.dpkg-tmp ] || exit 40
        \\    if [ '{s}' = 1 ]; then
        \\        [ -f /{s}/obsolete ] || exit 42
        \\        IFS= read -r obsolete < /{s}/obsolete || exit 43
        \\        [ "$obsolete" = 'only in 1' ] || exit 44
        \\    fi
        \\    /backup-probe-rm -f /backup-before || exit 41
        \\fi
        \\
    , .{
        base,                                                suffix, base,   base,    suffix,  base, base, base, base,
        if (std.mem.eql(u8, version, "1")) "600" else "640", base,   suffix, version, version, base, base,
    });
}

fn backupRoutes(fixture: *foundation.Fixture, driver: []const u8, dpkg: []const u8, arch: []const u8) !void {
    const selection = chosen(arch);
    for ([_]bool{ false, true }) |diverted| {
        const suffix = if (diverted) ".distrib" else "";
        var packages: [2][]u8 = undefined;
        for ([_][]const u8{ "1", "2" }, 0..) |version, index| {
            const probe = try backupScript(fixture, version, suffix);
            defer fixture.allocator.free(probe);
            const script = try std.mem.concat(fixture.allocator, u8, &.{ hook, probe });
            defer fixture.allocator.free(script);
            const conf = try std.fmt.allocPrint(fixture.allocator, "configuration {s}\n", .{version});
            defer fixture.allocator.free(conf);
            packages[index] = try support.makePackage(fixture, arch, version, name, if (diverted) "packages/backup-diverted" else "packages/backup-undiverted", .{
                .full_payload = true,
                .conffile_content = conf,
                .scripts = .{ .before_failure = script },
            });
        }
        defer for (packages) |built| fixture.allocator.free(built);
        for ([_][]const u8{ "success", "unwind", "rollback" }) |outcome| {
            const label = try std.fmt.allocPrint(fixture.allocator, "unpack-backups-{s}-{s}", .{ if (diverted) "true" else "false", outcome });
            defer fixture.allocator.free(label);
            var case = try support.Scenario.init(fixture, label, driver, dpkg, arch, false);
            defer case.deinit();
            for ([_][]const u8{ "reference", "native" }) |side| {
                const root = try support.path(fixture.allocator, label, side);
                defer fixture.allocator.free(root);
                try support.copyProgram(fixture, root, "/usr/bin/stat", "/backup-probe-stat");
                try support.copyProgram(fixture, root, "/usr/bin/rm", "/backup-probe-rm");
            }
            if (diverted) {
                const records = try record(fixture, base ++ "/data", base ++ "/data.distrib", ":");
                defer fixture.allocator.free(records);
                try seed(&case, records);
            }
            try case.seed(packages[0]);
            if (!std.mem.eql(u8, outcome, "success")) try failures(&case, if (std.mem.eql(u8, outcome, "rollback"))
                &.{ name ++ "@1:postrm:upgrade", name ++ "@2:postrm:failed-upgrade" }
            else
                &.{name ++ "@1:postrm:upgrade"});
            try case.phase(.{
                .operation = "upgrade",
                .archives = &.{packages[1]},
                .packages = &selection,
                .rollback_links = if (std.mem.eql(u8, outcome, "rollback")) &.{base ++ "/current"} else &.{},
            }, std.mem.eql(u8, outcome, "rollback"));
            for ([_][]const u8{ "reference", "native" }) |side| {
                for ([_][]const u8{ "data", "data.link", "mode", "current" }) |member| {
                    const changed = try std.fmt.allocPrint(fixture.allocator, "{s}/{s}/{s}/{s}{s}.dpkg-tmp", .{
                        label, side, base, member, if (std.mem.eql(u8, member, "data")) suffix else "",
                    });
                    defer fixture.allocator.free(changed);
                    if (diverted and std.mem.eql(u8, outcome, "rollback") and std.mem.eql(u8, member, "data")) {
                        const bytes = try support.read(fixture, changed, 64 * 1024);
                        defer fixture.allocator.free(bytes);
                        if (!std.mem.eql(u8, bytes, "data version 1\n")) return error.WrongUnpackBackup;
                    } else try support.absent(fixture, changed);
                }
                const marker_path = try std.fmt.allocPrint(fixture.allocator, "{s}/{s}/backup-before", .{ label, side });
                defer fixture.allocator.free(marker_path);
                try support.absent(fixture, marker_path);
            }
            if (std.mem.eql(u8, outcome, "success")) try case.phase(.{
                .operation = "reinstall",
                .archives = &.{packages[1]},
                .packages = &selection,
            }, false);
        }
    }
}

pub fn run(fixture: *foundation.Fixture, driver: []const u8, dpkg: []const u8, arch: []const u8) !void {
    const first = try archive(fixture, arch, "1", false);
    defer fixture.allocator.free(first);
    const second = try archive(fixture, arch, "2", false);
    defer fixture.allocator.free(second);
    try staticRoutes(fixture, driver, dpkg, arch, first, second);
    try unsafeRoutes(fixture, driver, dpkg, arch, first);
    try dynamicRoutes(fixture, driver, dpkg, arch, first, second);
    try failureRoutes(fixture, driver, dpkg, arch, first, second);
    try conffileRoutes(fixture, driver, dpkg, arch, first, second);
    try aliasRoutes(fixture, driver, dpkg, arch);
    try backupRoutes(fixture, driver, dpkg, arch);
}

test "backup probe requires real inode, link, mode and old payload before script failure" {
    var fixture = try foundation.Fixture.init(std.testing.allocator, std.testing.io, @import("native_test_options").repository);
    defer fixture.deinit();
    for ([_][]const u8{ "1", "2" }) |version| {
        const script = try backupScript(&fixture, version, ".distrib");
        defer std.testing.allocator.free(script);
        for ([_][]const u8{
            "data.distrib.dpkg-tmp", "mode.dpkg-tmp",                     "current.dpkg-tmp",
            "\"$original_data\"",    "backup-probe-rm -f /backup-before", "obsolete",
        }) |phrase| try std.testing.expect(std.mem.indexOf(u8, script, phrase) != null);
        try fixture.write("probe.sh", script, 0o755);
        const script_path = try fixture.absolute("probe.sh");
        defer std.testing.allocator.free(script_path);
        try fixture.run(&.{ "/bin/sh", "-n", script_path }, "probe-syntax.log", 10);
    }
}
